### ISSUE TITLE
Doesn't work when adding /usr/sbin/screencapture command

### ISSUE THREAD

**Issue by shooter556** [luckman212/screencapture-nag-remover#3]
I'm using 15.0.1

Like the title,
```
./screencapture-nag-remover.sh -a "/usr/sbin/screencapture"
```
but by "-p" it shows nothing be added. Yes, triggering screencapture still gives me that window.

It really works when I add terminal app to the plist.
```
./screencapture-nag-remover.sh -a "/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal"
```

Then "-p" show me next
```
{
  "/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal" => 2124-10-05 22:36:26 +0000
}
```

Same thing happens when I try to add "/usr/sbin/cron".

**Comment by luckman212** [comment]
The problem is because I believe this bypass only works for App Bundles (.app). Not sure it makes sense for it to add entries for commandline tools like screencapture (or cron?)

It's a simple fix (I just pushed a beta version you can try) but please let me know if this actually solves any problem for you.

Because on my system at least (also 15.0.1) when I execute `/usr/sbin/screencapture` the TCC alert says that "**iTerm2** is requesting to bypass..." — so it's whatever terminal you execute screencapture from that needs the permission granted I think.

**Comment by shooter556** [comment]
Yes it does work when adding terminal app to the bypass, then I trigger screencapture from the "Terminal.app".
But I also set a screencapture command in cron, and it will be triggered by cron instead of "Terminal". It runs at the background.
The result is , every 2 mins the GUI will bounce a window telling me that "cron is trying to bypass blabla..."
Even I clicked the "allow for one month" but it didn't work somehow.
I think this is not a  wonderful security enhancement upgrade in macos history.

**Comment by luckman212** [comment]
@shooter556 Ok please test the 1.3.1 beta and let me know if that works for you!

**Comment by luckman212** [comment]
I don't think this is a problem with my script, and so it probably isn't something I can fix. 

Still, can you provide the rest of your configuration so I can try to replicate your scenario and see if there's any solution? Please send your crontab and whatever other related scripts you're using if possible.

**Comment by shooter556** [comment]
You did a splendid job.
I really hope apple can improve this in future version, by supporting disabling switch.
